### ISSUE TITLE
Lab-05-enable-sql-defender-and-data-classification: outdated Security menu screenshot

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#10]
# Module: 03
#### Step: 10 -11

Description of issue
Outdated screenshots of the Security menu:

![image](https://user-images.githubusercontent.com/46898093/172367400-d382f05c-3954-4173-addf-e5247d9683ca.png)

![image](https://user-images.githubusercontent.com/46898093/172367866-db33694b-cbc6-45a1-b5a3-b258075876af.png)

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The screenshot has been updated.
