### ISSUE TITLE
Lab-05-enable-sql-defender-and-data-classification: auto-type not configured

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#12]
# Module: 03
#### Step: 5

Description of issue
Auto-type and copy activities are not working:
![image](https://user-images.githubusercontent.com/46898093/172370417-2e7604ec-51a1-498b-954d-e1ba7688a38f.png)

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The module [Implement compliance controls for sensitive data] is on the queue to be released, including a new lab profile and instructions for this lab.
