### ISSUE TITLE
Lab-08-identify-resolve-blocking-issues: query syntax error due to auto-type option part 2

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#16]
# Module: 05
#### Step: 01-03
Description of issue

Error:
![image](https://user-images.githubusercontent.com/46898093/172576382-462fbe28-68a9-4715-9c5a-5a4bf115df5c.png)

Suggestion to fix all those syntax errors: install SSMS and disable the IntelliSense option in the VM image.
![image](https://user-images.githubusercontent.com/46898093/172576518-07bfb46b-88e7-42a0-aa3a-1c04ebf3269d.png)

**Comment by JulianePadrao** [comment]
Thanks for your comment.

Before initiating the labs, we have the following alert note part of the instruction: When copying code from the lab exercises into the lab virtual machine, occasionally line breaks will not come across properly. Please verify that the code is correctly copied before executing it.

We also think the IntelliSense is an important tool for students during the lab.

For now we will keep this issue closed, and we can reevaluate it later on if needed.
