### ISSUE TITLE
Lab 02-provision-sql-database: remove point to select "Region"

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#2]
# Module: 01
#### Step: 04

Description of issue
As the Resource Group is already available in the lab environment, I suggest removing the following point:
"Region: Select the same region where your resource group was created", this field will be pre-populated when the learner chooses the Resource group. 
![image](https://user-images.githubusercontent.com/46898093/172142566-16568780-1834-4773-aff9-18324f2e07b6.png)

Or refer to suggestion of https://github.com/MicrosoftLearning/dp-300-database-administrator/issues/3.

**Comment by JulianePadrao** [comment]
Thanks for your feedback.

There are cases where the learner may not choose to use the lab environment provided. For those cases, we need to enforce the region selection - even though it may look redundant.
