### ISSUE TITLE
Lab-10-isolate-problem-areas-poor-performing-queries: load is not showing in Query Store

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#20]
# Module: 05
#### Step: 05-06, 08

Description of issue
After executing the script CreateRandomWorkloadGenerator.sql, I cannot see the load in query store. Isnt the script only creating the objects (stored procedures) and we are missing a script to call those sps?

![image](https://user-images.githubusercontent.com/46898093/172665968-2987ef2c-a8cb-494b-9d73-f4133f374526.png)

**Comment by JulianePadrao** [comment]
Thanks for your submission.

Issue has been addressed.
