### ISSUE TITLE
Lab-11-deploy-azure-database-using-template: replace copy activity by an auto-type

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#21]
# Module: 06
#### Step: 03

Description of issue

Suggest replacing the copy by auto-type functionality:
![image](https://user-images.githubusercontent.com/46898093/172801491-2d65d5bb-483a-4a67-8327-e5fa47d800f9.png)

Copy functionality is not working even I used the "Type Clipboard Text" option offered by Skillable.

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The module [Configure automatic deployment for Azure SQL Database] is on the queue to be released, including a new lab profile and instructions for this lab.
