### ISSUE TITLE
Lab-13-deploy-automation-runbook-rebuild-indexes: create an Automation Account process is outdated

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#22]
# Module: 06
#### Step: 01-03

Description of issue

01- Cannot find the option "Add"

![image](https://user-images.githubusercontent.com/46898093/172830636-8cc6b6c6-92ea-4640-a905-b569a8cc0693.png)

02 - Please review the screenshot:
![image](https://user-images.githubusercontent.com/46898093/172831050-b5d77892-91e3-4d08-8527-4232f1874f68.png)

03- Review instructions and screenshot as per steps executed before.

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The module [Manage Azure PaaS resources using automated methods] is on the queue to be released, including a new lab profile and instructions for this lab.
