### ISSUE TITLE
Lab-13-deploy-automation-runbook-rebuild-indexes: outdated screenshot add firewall rule

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#23]
# Module: 06
#### Step: 03-04

Description of issue

Outdated screenshot and process to add the firewall exception:

![image](https://user-images.githubusercontent.com/46898093/172831804-5d4fbad4-a0ba-4fce-a6bb-569beae18b4a.png)

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The module [Manage Azure PaaS resources using automated methods] is on the queue to be released, including a new lab profile and instructions for this lab.
