### ISSUE TITLE
Lab-13-deploy-automation-runbook-rebuild-indexes: outdate instructions and screenshot to import modules within Gallery

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#24]
# Module: 06
#### Step: 07-08

Description of issue

07-
![image](https://user-images.githubusercontent.com/46898093/172833138-233783ad-af1d-49b7-a39a-7b9b05e5a7b7.png)

08-
![image](https://user-images.githubusercontent.com/46898093/172833245-7e04f80a-5315-4464-8955-892506c0d161.png)

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The module [Manage Azure PaaS resources using automated methods] is on the queue to be released, including a new lab profile and instructions for this lab.
