### ISSUE TITLE
Lab-13-deploy-automation-runbook-rebuild-indexes: outdated screenshots and instructions schedule

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#25]
# Module: 06
#### Step: 03

Description of issue
 outdated screenshot and instructions:

![image](https://user-images.githubusercontent.com/46898093/172835058-9b739fb8-ad2d-426f-9ac5-e3efff6c004e.png)

After creating it, it is when you have to go back to the runbook, select it and Link to schedule. 

![image](https://user-images.githubusercontent.com/46898093/172835349-0ed37f02-4fa0-473c-acf3-b2da84efdec2.png)

Alternatively, you can navigate to the runbook and create the schedule from there selecting the Link to schedule option.

Similar issue has been reported at: DP-300T00-Administering-Relational-Databases-on-Azure repository ([https://github.com/MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure/issues/147])

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The module [Manage Azure PaaS resources using automated methods] is on the queue to be released, including a new lab profile and instructions for this lab.
