### ISSUE TITLE
Lab-15-backup-url: suggestion to replace the database for the LT version to minimize the time taken to backup and restore during the exercise

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#27]
# Module: 07
#### Step: 01-04

Description of issue
Replacing the current backup to the AdventureWorksLT2017 version, reduce significantly the time taken to perform the Backup to URL / Restore from URL steps.

The restore database commands and backup need to be modified to adapt to AdventureWorksLT2017 DB, in the **Restore from URL** task, the steps 1 and 2 also require a small update:

step: 1
```
USE AdventureWorksLT2017;
GO
SELECT * FROM SalesLT.Address WHERE AddressId = 9;
GO
```

step: 2
```
UPDATE SalesLT.Address
SET AddressLine1 = 'This is a human error'
WHERE AddressId = 9;
GO
```

**Comment by JulianePadrao** [comment]
Currently the backup and restore operation take  only a few seconds.
We will monitor and evaluate in case the backup/restore duration starts impacting the completion of the labs.

Thanks
