### ISSUE TITLE
Module 2 Instructions on VNET Creation doesn't match new Interface Changes 

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/dp-300-database-administrator#28]
# Module: 02
#### Step: 02 and 03

On step 2, you need to click on Security button first, then the IP Addresses button.

![Lab 2 Issue 1](https://user-images.githubusercontent.com/16696370/200408095-afaddece-58d4-4ce6-a3c0-3c764c7daa69.png)

On step 3, when you click on the default subnet, there is no longer an option to edit the service endpoints at creation time.  You need to go back and edit the created VNET and add the Service Endpoint of microsoft.sql at that time

![Lab 2 Issue 2](https://user-images.githubusercontent.com/16696370/200409061-38753964-8de6-4d2c-a982-c4cc5ab75f7f.png)
.

Repro steps:

1.
1.
1.

**Comment by JulianePadrao** [comment]
Thanks for your feedback, this issue has been addressed.
