### ISSUE TITLE
Module 2 Instructions don't match interface

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/dp-300-database-administrator#29]
# Module: 02
#### Step: 04

When creating the logical server, the interface defaults to "Use only Azure Active Directory (Azure AD) authentication". A step needs to be added to say Under Authentication Mode, select "Use SQL authentication".

![Lab 2 Issue 3](https://user-images.githubusercontent.com/16696370/200412875-65c091f5-adec-4ee6-8370-1aa04c59222c.png)
 
Also, in the  Compute + Storage: Click Configure database section, the graphic needs to be updated and the instructions should state, "under Service Tier, select "Basic (For less demanding workloads)".
![Lab 2 Issue 4](https://user-images.githubusercontent.com/16696370/200414206-b97732c1-5244-4246-bf9d-41ae7bea2880.png)

Description of issue

Repro steps:

1.
1.
1.

**Comment by JulianePadrao** [comment]
The issue has been addressed, thanks for your feedback.
