### ISSUE TITLE
Lab 02-provision-sql-database: add a step to get the Resource Group "Location"

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#3]
# Module: 01
#### Step: 00

Description of issue:
I suggest adding a step to check the Resource Group information before start provisioning the SQL DB as the information is asked in step 3. Or even before creating the Vnet.

While creating the Logical Server:

The instruction says:
Location: <your local region, same as the selected region for your resource group, otherwise it may fail>

By default, this field maybe pre-populated with wrong information. Therefore, it is important to check the correct Resource Group Region/Location.

Suggestion:
From the Azure Portal, search for “Resource groups” in the search box at the top, then click Resource groups from the list of options. Keep a note of the Location of your Resource Group which you will use in subsequent steps while creating resources.

**Comment by JulianePadrao** [comment]
Thanks for your submission. The instruction has been updated with the steps to find the resource group location.
