### ISSUE TITLE
Module 2 Lab Missing Step

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/dp-300-database-administrator#30]
# Module: 02
#### Step: 03

Description of issue:
It states, "On the Public access tab, check the Allow Azure services and resources to access this server property, and then click Save."  It should state "In the Set Public Access" section, select "Selected Networks" before it. 

![Lab 2 Issue 5](https://user-images.githubusercontent.com/16696370/200434273-ffc937b3-f080-465d-b05f-3af4d53f0642.png)
Repro steps:

1.
1.
1.

**Comment by JulianePadrao** [comment]
The issue has been addressed. Thanks for your feedback.
