### ISSUE TITLE
UPDATE: UI Change

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/dp-300-database-administrator#31]
# Module: 00
#### Step: 07

Description of issue
UI for email has been moved to linked page. 

BUG: Student AAD account did not have rights to set email address.

Repro steps:

1.
1.
1.

**Comment by TesterTesterson1004** [comment]
This issue is still a problem, and although separate/custom 'alerts' can be created to embellish the instructions here in GH, would it be possible to update GH to address this?

**Comment by JulianePadrao** [comment]
Thanks for your feedback. This issue has been addressed.
