### ISSUE TITLE
13-deploy-automation-runbook-rebuild-indexes.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/dp-300-database-administrator#34]
# Module: 00
#### Step: 03

Description of issue

In section 'Create an Automation Account', Step 3, the screenshot references a pre-created Resource Group called <contoso-rglod########>, whereas the instructions say 'Resource Group: starting with **automateLab**'

I think all of the rest of the labs use the pre-created RG name of <contoso-rglod########> so I think it is meant to use that in this lab as well? (Instead of 'automateLab'?)

**Comment by JulianePadrao** [comment]
Thanks for your feedback, this issue has been fixed.
