### ISSUE TITLE
Update Lab Instructions for Labs 3, 4, 5, 6, 12, 13, and 14 > notification of existing resources

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#36]
The instructions for **Labs 3, 4, 5, 6, 12, 13, and 14** currently rely on **existing resources and SQL databases**.

I would like to request that we update the instructions for these labs by adding a note at the beginning to notify learners about the use of existing resources and SQL databases. This would provide clarity and help learners better understand the lab requirements.

**Comment by JulianePadrao** [comment]
The issue has been addressed. Thanks for your feedback.
