### ISSUE TITLE
updated reference to SSMS 19

### ISSUE THREAD

**Issue by jkulbe-msft** [MicrosoftLearning/dp-300-database-administrator#38]
# Module: 00
#### Step: 6

Description of issue

Description shows outdated text and screenshot referring to SSMS 18, while Azure now deploys SSMS 19. Suggested fix in text and imagery is in pull request #37 (https://github.com/MicrosoftLearning/dp-300-database-administrator/pull/37)

**Comment by JulianePadrao** [comment]
This issue has been addressed. Thanks for your feedback.
