### ISSUE TITLE
Lab 3, "database " and 'server" confusion

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/dp-300-database-administrator#39]
# Module: 03-authorize-access-azure-sql-database.md
#### Step: 3

Replace 
"Select the Azure SQL Database server dp300-lab-xxxxxx"
With 
"Select the SQL server dp300-lab-xxxxxx"

I know it's a little change, but I've seen this confused many times. 

Also, the difference between an Azure SQL Server and an Azure SQL Database is actually pretty important.

**Comment by JulianePadrao** [comment]
We're looking into this issue, thank you.

**Comment by JulianePadrao** [comment]
This issue has been addressed. Thank you for your feedback.
