### ISSUE TITLE
Some praise

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/dp-300-database-administrator#40]
This is not an issue, I just thought I'd pass on some praise that came out of our class review this morning.

I really like the way the labs use Azure Data Studio, in particular the use of a Jupyter notebook. It's a nice feature of the product and none of the other courses and labs seem to mention it. 

Thanks for including it in the first lab in this course.

**Comment by JulianePadrao** [comment]
Thank your feedback, I'm glad you've found the Jupyter notebook feature useful.
