### ISSUE TITLE
Lab13-Automation Runbook

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/dp-300-database-administrator#41]
# Lab 13-Automation Runbook

The lab works correctly as written, but that's because you don't actually execute the runbook.   I've tried with both PowerShell Runtime 7.1 and 7.2, and either way the runbook does not execute correctly.   It has an issue with the term "Invoke-Sqlcmd.'   You get an exception like this:

![image](https://github.com/MicrosoftLearning/dp-300-database-administrator/assets/72703514/f6635785-01fe-472e-a744-2653a25cbe7f)

Here's the text of the error message:
[91mInvoke-Sqlcmd: [0mC:\usr\src\tmp\eb604bd7-581f-4412-8291-fff8b0fd6878\runbooks\Indexv2.ps1:5 [96mLine | [96m 5 | [0m $SQLOutput = $([96mInvoke-Sqlcmd[0m -ServerInstance $AzureSQLServerName -Use … [96m | [91m ~~~~~~~~~~~~~ [91m[96m | [91mThe term 'Invoke-Sqlcmd' is not recognized as a name of a [96m | [91mcmdlet, function, script file, or executable program. Check [96m | [91mthe spelling of the name, or if a path was included, verify [96m | [91mthat the path is correct and try again. [0m

It would be nice to execute the runbook and not have any errors.   I'm just not familiar enough to know what the issue is with PowerShell.

**Comment by tylerfarmer1** [comment]
Any thoughts on this?  I opened this ticket 2 months ago.

**Comment by JulianePadrao** [comment]
We're looking into this issue, thank you.

**Comment by afelix-95** [comment]
The problem might have been adding the **SqlServer** module with the Runtime version of 7.1, since that version is no longer supported by PowerShell. With both the runbook and the module set with Runtime 7.2 I was able to run it without any errors.
