### ISSUE TITLE
Module 2 - Slide content error

### ISSUE THREAD

**Issue by pasqualeceglie** [MicrosoftLearning/dp-300-database-administrator#42]
# Module: 2
## Slide: 38

Error on the slide "Azure SQL Database service tier options". Both the sections have the same title "Service tier options - DTU" instead of 
"Service tier options - DTU" and "Service tier options - vCore"

![image](https://github.com/MicrosoftLearning/dp-300-database-administrator/assets/46398371/27d71d5d-ed96-424f-ab6f-6b53fda195e5)

**Comment by JulianePadrao** [comment]
This will be added to the next release of the module. Thanks for your feedback.
