### ISSUE TITLE
Lab 1 - Need checkbox for SSMS v.20

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/dp-300-database-administrator#43]
# Lab/Demo: 01 - Provision SQL Server on Azure VM
## Section - Connect to SQL Server on an Azure Virtual Machine

Description of issue

Two issues, both relatively minor:

1. The Azure portal has changed just a bit when connecting to a VM through RDP
- Step 1 of the instructions say:
"On the Overview page for the virtual machine, select the Connect button and choose RDP."

It should be changed to something like:
"On the Overview page for the virtual machine, select the Connect dropdown and select Connect."
Then step 2 should be just "Select the Download RDP File button."   The picture is out of date, but it should be workable.

2.  The SQL VM now includes the newer version of SSMS - version 20.   With v.20, when you're on the login page to connect to SQL Server, the is a checkbox called "Trust Server Certificate" that must be turned on.  Otherwise you won't be able to connect to the SQL Server.  So the instructions on Step 7 need to include a new picture, and include the action to "Turn on the checkbox for Trust Server Certificate."

**Comment by JulianePadrao** [comment]
We're looking into this issue, thank you.

**Comment by afelix-95** [comment]
Thank you for pointing those out! The lab is updated.
