### ISSUE TITLE
Lab-15-backup-url: unable to execute query. Cannot open backup device

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/dp-300-database-administrator#44]
# Module: 00
#### Step: 00

Description of issue
Unable to backup to URL. 
<img width="270" alt="image" src="https://github.com/MicrosoftLearning/dp-300-database-administrator/assets/24426530/57b47d08-0982-4ac7-95b0-cdb5702ace18">

I have verified Container exists

I notice there is red on both sides of the string

<img width="622" alt="image" src="https://github.com/MicrosoftLearning/dp-300-database-administrator/assets/24426530/efb5532d-914d-4226-b7dc-d942886ed161">
<img width="301" alt="image" src="https://github.com/MicrosoftLearning/dp-300-database-administrator/assets/24426530/3b2b11e6-7296-47ca-94df-86366dd498a1">

<img width="494" alt="image" src="https://github.com/MicrosoftLearning/dp-300-database-administrator/assets/24426530/f114d243-3f99-4159-8b70-f5d3bbc5731c">

<img width="358" alt="image" src="https://github.com/MicrosoftLearning/dp-300-database-administrator/assets/24426530/e95c3663-47da-4261-b400-ba34b8db3bca">

Repro steps:

1.
1.
1.

**Comment by JulianePadrao** [comment]
We're looking into this issue, thank you.

**Comment by afelix-95** [comment]
I could still upload the backup according to the instructions. There could have been some mistake when creating the credential, since that step doesn't throw any errors if created incorrectly. Closing it as no repro.
