### ISSUE TITLE
Lab 02-provision-sql-database: security options are outdated

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#5]
# Module: 01
#### Step: 01-03

Description of issue
Add an extra comment to point to the overview navigation blade
1. From the SQL database page, **Overview navigation blade**, click on the link for the server name in the top section.
2. On the SQL servers **page, Overview navigation blade,** click <strike>Firewalls and virtual networks</strike> **Networking** under Security .
Note: The screenshot is out of date.
![image](https://user-images.githubusercontent.com/46898093/172160258-a4d3cbe6-8426-4928-94e7-5ce1d0cb2150.png)

3.  The screenshot is out of date.
![image](https://user-images.githubusercontent.com/46898093/172160606-a1319db5-a006-43be-b102-eff9bb35204d.png)

**Comment by JulianePadrao** [comment]
Thanks for your feedback.

The instruction has been updated.
