### ISSUE TITLE
Lab 02-provision-sql-database: Azure Data Studio firewall exception does not work

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#6]
# Module: 01
#### Step: 03

Description of issue

1. Duplicate the instructions: Provision an Azure SQL Database > step 3:

- Server name:  XXXXX (adding **database.windows.net** as suffix) 
- Server admin login: dp300admin
- Password: dp300P@ssword!

2. In Azure Data Studio, account option is not working:

![image](https://user-images.githubusercontent.com/46898093/172162503-62fae2a1-b7d0-466e-8309-4763ace2ddd7.png)

Another attempt: several minutes in the login page and no sucess: 
![image](https://user-images.githubusercontent.com/46898093/172163340-4a27f330-42f0-4cf7-9911-5a5f8109fae9.png)

Alternatively, you can ask the learners to add the firewall exception from, **SQL Server** page, **Networking** blade under **Security**, **Firewall rules**, click on **Add your client IPv4 address**, then click on **Save**:

![image](https://user-images.githubusercontent.com/46898093/172163240-7db2323e-baa0-41df-9d60-758abdb0603f.png)

**Comment by JulianePadrao** [comment]
Thanks for your submission. 

It seems after the lab went live the firewall rule creation is not working from ADS. The sign in for me runs indefinitely. I have included the workaround.
