### ISSUE TITLE
Lab-03-authorize-access-azure-sql-database: improvements to add a AAD Admin and outdated screenshot

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#7]
# Module: 03
#### Step: 03, 05

Description of issue:

Step 3: Screenshot is outdated:
![image](https://user-images.githubusercontent.com/46898093/172166827-81f780bd-29f4-4e70-97c2-159c5b3fb373.png)

Step 5: Instruction:
In the Azure Active Directory sidebar, search for the Azure username you logged into the Azure portal with, ***(I suggest adding a remark, "the **Username** provided on the Resources tab for this lab virtual machine")***, then click on Select.
Connect to the Portal using the Azure Username and Password provided on the Resources tab for this lab virtual machine.

**Comment by JulianePadrao** [comment]
Thanks for your submission. The screenshot was updated. 

Since these labs are being used by different lab providers, the suggestion for Step 5 can't be updated at this point.
