### ISSUE TITLE
Lab-04-configure-firewall-rule: Networking settings outdated screenshot and info

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#8]
# Module: 03
#### Step: 04-06
Description of issue
Please refer to info related to [this issue in the current repository used for ILT](https://github.com/MicrosoftLearning/DP-300T00-Administering-Relational-Databases-on-Azure/issues/140)

**Comment by JulianePadrao** [comment]
Thanks for your submission.

The instruction has been updated.
