### ISSUE TITLE
Lab-04-configure-firewall-rule: improvement related to the time taken to Import Data Tier Application task

### ISSUE THREAD

**Issue by vipaiva** [MicrosoftLearning/dp-300-database-administrator#9]
# Module: 03
#### Step: 09-15

Description of issue
The tasks related to Import Data Tier Application takes over 30min with the current bacpac file. I suggest creating a new bacpac file for [AdventureWorksLT2019](https://github.com/Microsoft/sql-server-samples/releases/download/adventureworks/AdventureWorksLT2019.bak)

![image](https://user-images.githubusercontent.com/46898093/172207095-33c4941b-dfe7-4d19-bf59-b57571814483.png)

Using the AdventureWorksLT2019 bacpac, the import task takes less than 5min without compromising the remaining steps.

**Comment by JulianePadrao** [comment]
Interesting to see it is taking so long as it is the same version that has been used before. I was not able to reproduce the long duration, in my case it was taking less than 10 minutes.

To prevent any issues, I have updated the lab to use the light version of AdventureWorks instead.

Thanks for pointing that out!
